- name: Install vim editor
  dnf:
    name: vim-enhanced
    state: latest
  become: yes

- name: Install lsof
  dnf:
    name: lsof
    state: latest
  become: yes

- name: Install extra package repo
  dnf:
    name: epel-release
    state: latest
  become: yes

- name: Install htop
  dnf:
    name: htop
    state: latest
  become: yes
