# sudo fallocate -l 1G /swapfile
# sudo chmod 600 /swapfile
# sudo mkswap /swapfile
# sudo swapon /swapfile

- name: Get stats for swapfile
  ansible.builtin.stat:
    path: /swapfile
  register: sym

- name: Allocate swap file
  ansible.builtin.shell: fallocate -l 4G /swapfile
  become: yes
  when: not sym.stat.exists

- name: Fix permission
  ansible.builtin.file:
    path: /swapfile
    state: file
    mode: 0600
  become: yes
  when: not sym.stat.exists

- name: Make swap
  ansible.builtin.shell: mkswap /swapfile
  become: yes
  when: not sym.stat.exists

- name: swapon
  ansible.builtin.shell: swapon /swapfile
  become: yes
  when: not sym.stat.exists

- name: Ensure swap is in /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: /swapfile none swap sw 0 0
  become: yes
