{
 "title": "Backup",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "backup_pg_dump_count" } }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "last pg age (days)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_last_pg_dump_age{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "last pg size (MB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_last_pg_dump_size{job=\"$job\"}/(1024*1024)"
    }
   ]
  },
  {
   "title": "last pg lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_last_pg_dump_lines{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "pg count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_pg_dump_count{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "pg size (MB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_pg_dump_size{job=\"$job\"}/(1024 * 1024)"
    }
   ]
  },
  {
   "title": "reports count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_reports_count{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "reports size (MB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_reports_size{job=\"$job\"}/(1024 * 1024)"
    }
   ]
  },
  { "title": "Content", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Last pg age (days)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "backup_last_pg_dump_age{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Last pg size (MB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "backup_last_pg_dump_size{job=\"$job\"} / (1024*1024)"
    }
   ]
  },
  {
   "title": "Last pg lines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "backup_last_pg_dump_lines{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "pg count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "backup_pg_dump_count{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "pg size (MB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "backup_pg_dump_size{job=\"$job\"} / (1024 * 1024)"
    }
   ]
  },
  {
   "title": "reports count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "backup_reports_count{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "reports size (MB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "backup_reports_size{job=\"$job\"} / (1024 * 1024)"
    }
   ]
  }
 ]
}