{
 "title": "Home",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "ed health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"ed.soklaki\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"ed.soklaki\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{job=\"ed.soklaki\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{job=\"ed.soklaki\"}) /  count(count(node_cpu_seconds_total{job=\"ed.soklaki\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"ed.soklaki\"} * 100) / node_memory_MemTotal_bytes{job=\"ed.soklaki\"})"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"ed.soklaki\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"ed.soklaki\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  { "title": "ed app", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_processing_seconds_sum{job=\"ed.app\"} / request_processing_seconds_count{job=\"ed.app\"}"
    }
   ]
  },
  {
   "title": "Failure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_failure_total{job=\"ed.app\"}"
    }
   ]
  },
  {
   "title": "Observation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eval_observation{job=\"ed.app\"}"
    }
   ]
  },
  {
   "title": "Evaluation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eval_evaluation{job=\"ed.app\"}"
    }
   ]
  },
  {
   "title": "Group",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group{job=\"ed.app\"}"
    }
   ]
  },
  {
   "title": "User",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user{job=\"ed.app\"}"
    }
   ]
  },
  { "title": "Backup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "ed last pg age (days)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_last_pg_dump_age{job=\"ed.backup\"}"
    }
   ]
  },
  {
   "title": "ed last pg lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_last_pg_dump_lines{job=\"ed.backup\"}"
    }
   ]
  },
  {
   "title": "ed pg count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_pg_dump_count{job=\"ed.backup\"}"
    }
   ]
  },
  {
   "title": "ed pg size (MB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_pg_dump_size{job=\"ed.backup\"}/(1024 * 1024)"
    }
   ]
  },
  {
   "title": "ed reports count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_reports_count{job=\"ed.backup\"}"
    }
   ]
  },
  {
   "title": "ed reports size (MB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_reports_size{job=\"ed.backup\"}/(1024 * 1024)"
    }
   ]
  },
  {
   "title": "staging last pg age (days)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_last_pg_dump_age{job=\"staging.backup\"}"
    }
   ]
  },
  {
   "title": "staging last pg lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_last_pg_dump_lines{job=\"staging.backup\"}"
    }
   ]
  },
  {
   "title": "staging pg count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_pg_dump_count{job=\"staging.backup\"}"
    }
   ]
  },
  {
   "title": "staging pg size (MB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_pg_dump_size{job=\"staging.backup\"}/(1024 * 1024)"
    }
   ]
  },
  {
   "title": "staging reports count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_reports_count{job=\"staging.backup\"}"
    }
   ]
  },
  {
   "title": "staging reports size (MB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_reports_size{job=\"staging.backup\"}/(1024 * 1024)"
    }
   ]
  },
  {
   "title": "prom last pg age (days)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_last_pg_dump_age{job=\"prom.backup\"}"
    }
   ]
  },
  {
   "title": "prom last pg lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_last_pg_dump_lines{job=\"prom.backup\"}"
    }
   ]
  },
  {
   "title": "prom pg count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_pg_dump_count{job=\"prom.backup\"}"
    }
   ]
  },
  {
   "title": "prom pg size (MB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_pg_dump_size{job=\"prom.backup\"}/(1024 * 1024)"
    }
   ]
  },
  {
   "title": "prom reports count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_reports_count{job=\"prom.backup\"}"
    }
   ]
  },
  {
   "title": "prom reports size (MB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_reports_size{job=\"prom.backup\"}/(1024 * 1024)"
    }
   ]
  }
 ]
}