- name: Install nginx
  dnf:
    name: nginx
    state: latest
  become: yes

- name: Enable nginx
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    state: started
  become: yes

- name: Allow nginx to proxy_pass
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  become: yes

- name: Root directories
  ansible.builtin.file:
    path: "{{ item.root }}"
    state: directory
  become: yes
  loop: "{{ domains }}"

- name: Simple index.html for each root
  ansible.builtin.copy:
    src: "{{ role_path }}/files/index.html"
    dest: "{{ item.root }}/index.html"
    mode: 0644
  become: yes
  loop: "{{ domains }}"

- name: Install dependency
  dnf:
    name: python3-passlib
    state: latest
  become: yes

- name: Add a user for administrator area
  community.general.htpasswd:
    path: /etc/nginx/.htpasswd
    name: "{{ admin_user }}"
    password: "{{ admin_password }}"
    owner: root
    group: nginx
    mode: 0640
  become: yes

- name: Nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
  become: yes

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
  become: yes
