version: 3
endpoint: http://localhost:8080
metadata_directory: metadata
admin_secret: "hasura admin secret - keep in sync with hasura deployment"
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:8000